"""Global state container for the LangGraph execution pipeline.

Defines the strictly typed state object that flows through all compiler
passes, nodes, and tools. Inherits from ScrygentBaseModel to guarantee
JSON-safe boundaries at every assignment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import Field

from ..base_model import ScrygentBaseModel
from .outputs import AnalysisReport, CSVProfile, DirectAnswer
from .step_models import Plan, StepRecord

JSONPrimitive = str | int | float | bool | None
type JSONType = JSONPrimitive | list["JSONType"] | dict[str, "JSONType"]
type ToolOutput = dict[str, JSONType] | list[JSONType] | JSONPrimitive


class AgentState(ScrygentBaseModel):
    """Central state container for a single query execution cycle.

    Enforces strict JSON serialization boundaries and controls LangGraph
    routing via execution_status transitions.
    """

    # System Configuration
    original_csv_path: Path = Field(description="Immutable path to the initial user-uploaded CSV. Never overwritten.")
    current_csv_path: Path = Field(description="Active path consumed by tools. Updated by wrangling operations.")
    user_query: str = Field(description="The original natural language query.")
    eval_mode: bool = Field(default=False, description="If True, Reporter outputs DirectAnswer. If False, outputs AnalysisReport.")
    has_replanned: bool = Field(
        default=False,
        description="Hard session-level guard against repeated lazy-fetch cycles. "
        "Planner may trigger exactly one mid-session profile augmentation per query.",
    )

    # Profiling
    data_profile: CSVProfile | None = Field(default=None, description="Two-level profile: global_schema, detailed_stats, and row_sample.")

    # Execution Plan
    plan: Plan | None = Field(default=None, description="Sequential list of steps generated by the Planner.")
    current_step_index: int = Field(default=0, description="Pointer to the active step in the plan.")

    # Execution Memory
    step_outputs: dict[str, ToolOutput] = Field(
        default_factory=dict, description="Accumulated JSON-safe results from completed steps, keyed by step_id."
    )
    retry_count: int = Field(default=0, description="Tracks correction loop attempts within the Executor for the current step.")
    error_log: list[str] = Field(default_factory=list, description="Non-fatal warnings, validation failures, and skipped step records.")

    # Routing & Control
    execution_status: Literal["pending", "running", "replan", "aborted", "complete"] = Field(
        default="pending", description="Primary state machine driver for conditional graph routing."
    )

    # Execution History
    execution_trace: list[StepRecord] = Field(default_factory=list, description="Compact audit trail for completed, failed, and skipped steps.")

    # Final Output
    final_report: AnalysisReport | DirectAnswer | None = Field(default=None, description="Synthesized output generated by the Reporter Node.")
