from __future__ import annotations
from pathlib import Path
from typing import Literal
from pydantic import Field

from .outputs import CSVProfile, AnalysisReport, DirectAnswer
from ..base_model import ScrygentBaseModel
from .step_models import Plan, StepRecord


# Strict Type Definitions for JSON execution memory.
type JSONPrimitive = str | int | float | bool | None
type JSONType = JSONPrimitive | list[JSONType] | dict[str, JSONType]

# All tools must return a valid JSON structure (dict, list, or primitive)
type ToolOutput = dict[str, JSONType] | list[JSONType] | JSONPrimitive


class AgentState(ScrygentBaseModel):
    """
    The AgentState class encapsulates the entire state of the agent 
    during a single user session. It is designed to be serializable to 
    JSON for persistence and recovery.
    """

    # System Configuration and Inputs
    original_csv_path: Path = Field(
        description="Immutable path to the initial user-uploaded CSV. Allows resetting state."
    )
    current_csv_path: Path = Field(
        description="Path to the active CSV. Updated by wrangling tools if data is transformed."
    )
    user_query: str = Field(
        description="The original natural language query from the user."
    )
    eval_mode: bool = Field(
        default=False,
        description="If True, Reporter outputs a DirectAnswer (benchmarking). If False, outputs AnalysisReport."
    )
    has_replanned: bool = Field(
        default=False,
        description=(
            "True once the single permitted lazy-fetch replan (triggered by a "
            "request_column_stats-only Plan) has occurred. The Planner may only "
            "request a mid-session profile augmentation once per query; this is "
            "the hard session-level guard against repeated lazy fetches, "
            "independent of and in addition to the plan-level structural "
            "constraint enforced in Plan._lazy_fetch_must_be_sole_step."
        ),
    )

    # Profiling Data
    data_profile: CSVProfile | None = Field(
        default=None,
        description="The two-level profile (global_schema + detailed_stats) + row sample."
    )
    
    # Execution Plan
    plan: Plan | None = Field(
        default=None,
        description="The sequential list of steps generated by the Planner."
    )
    current_step_index: int = Field(
        default=0,
        description="Pointer to the active step in the Plan."
    )
    
    # Execution Memory
    step_outputs: dict[str, ToolOutput] = Field(
        default_factory=dict,
        description="Accumulated JSON-safe results from completed steps, mapped by step ID."
    )
    retry_count: int = Field(
        default=0,
        description="Tracks correction loop attempts within the Executor Node for the current step."
    )
    error_log: list[str] = Field(
        default_factory=list,
        description="Non-fatal warnings, Pydantic validation failures, and skipped step records."
    )
    
    # Routing & Control
    execution_status: Literal["pending", "running", "replan", "aborted", "complete"] = Field(
        default="pending",
        description="Drives conditional routing in the graph builder."
    )

    # Execution History
    execution_trace: list[StepRecord] = Field(
        default_factory=list,
        description="Compact audit trail for completed, failed, and skipped steps."
    )
    
    # Final Output
    final_report: AnalysisReport | DirectAnswer | None = Field(
        default=None,
        description="The synthesized output generated by the Reporter Node."
    )
