from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field, model_validator


class Step(BaseModel):
    """
    A single unit of work within a Plan, generated by the Planner Node
    and consumed by the Executor Node.
    """

    step_id: str = Field(
        description="Unique identifier for this step, used as the key in AgentState.step_outputs."
    )
    action: Literal["tool", "sandbox"] = Field(
        description="Whether this step dispatches a Tier 1 tool or escalates to the Tier 2 sandbox."
    )
    tool_name: str | None = Field(
        default=None,
        description="Name of the registered Tier 1 tool to call (e.g. 'analyze_data', "
        "'request_column_stats', 'correlation'). Required when action == 'tool'.",
    )
    parameters: dict[str, str | int | float | bool | None] = Field(
        default_factory=dict,
        description="Typed keyword arguments passed to the tool dispatch. Unused for sandbox steps.",
    )
    instruction: str | None = Field(
        default=None,
        description="Natural-language description of the computation to perform. Required when "
        "action == 'sandbox'. Never contains executable code.",
    )
    required: bool = Field(
        default=True,
        description="If True and this step exhausts its correction retries, execution_status is "
        "set to 'aborted'. If False, the failure is logged to error_log and execution proceeds.",
    )

    @model_validator(mode="after")
    def _validate_action_payload(self) -> "Step":
        if self.action == "tool" and not self.tool_name:
            raise ValueError("Step.tool_name is required when action == 'tool'.")
        if self.action == "sandbox" and not self.instruction:
            raise ValueError("Step.instruction is required when action == 'sandbox'.")
        return self


class Plan(BaseModel):
    """
    The full execution plan produced by a single Planner LLM call via
    with_structured_output(). Consumed step-by-step by the Executor.
    """

    steps: list[Step] = Field(
        description="Ordered list of steps to execute. The Executor advances through this list "
        "using AgentState.current_step_index."
    )


class CSVProfile(BaseModel):
    """
    The deterministic, two-level structural summary produced by the Profiler Node.
    See ARCHITECTURE.md Section 2 ("State & Models") and DESIGN.md "The Fixed
    Plan-and-Execute Loop", step 1.
    """

    global_schema: dict[str, str] = Field(
        description="Column name -> dtype string for EVERY column in the CSV, regardless of "
        "width. Prevents the 'Profiler Blind Spot' by ensuring the Planner always sees the "
        "full schema, even for columns excluded from detailed_stats."
    )
    detailed_stats: dict[str, dict[str, str | int | float | None]] = Field(
        default_factory=dict,
        description="Full statistical metrics (dtype, null_rate, unique_count, and min/max/mean "
        "for numeric columns) for columns matched by the strict whole-word query regex, plus the "
        "top MAX_DETAILED_COLUMNS columns by completeness."
    )
    row_sample: list[dict[str, str | int | float | bool | None]] = Field(
        default_factory=list,
        description="A 3-row sample with NaN cells replaced by None, used solely for LLM format "
        "inference (e.g. date patterns). Never used as a source of bulk data."
    )
    truncated: bool = Field(
        default=False,
        description="True if detailed_stats covers fewer columns than exist in global_schema. "
        "Signals to the Planner that request_column_stats may be needed for additional columns."
    )


class PlotMetadata(BaseModel):
    """A single saved visualization referenced from an AnalysisReport."""

    file_path: str = Field(description="Disk path to the saved plot image. Never a base64 blob.")
    description: str = Field(description="Short natural-language description of what the plot shows.")


class AnalysisReport(BaseModel):
    """
    The default Reporter Node output (eval_mode == False). The portfolio-facing,
    narrative report.

    primary_answer is required and must be populated before additional_insights,
    per the Reporter Pydantic isolation decision in DESIGN.md ("What We Decided Not
    to Build" -> Explorer Node): this guarantees the user's question is answered
    accurately before any secondary content is generated.
    """

    primary_answer: str = Field(
        description="Direct answer to the user's original query, derived strictly from "
        "verified Tier 1 / Tier 2 tool outputs. Must be populated first."
    )
    additional_insights: list[str] | None = Field(
        default=None,
        description="Optional secondary observations surfaced only from tool outputs already in "
        "context. Never populated at the expense of primary_answer, and never sourced from a "
        "proactive anomaly scan (no Explorer Node)."
    )
    plots: list[PlotMetadata] = Field(
        default_factory=list,
        description="File paths and descriptions of visualizations generated during execution."
    )


class DirectAnswer(BaseModel):
    """
    The Reporter Node output when eval_mode == True. Used exclusively for formal
    benchmarking (InfiAgent-DABench, DataBench Lite). No narrative, no plots —
    only the answer value in the format the benchmark evaluation harness expects.
    """

    answer: str = Field(
        description="The extracted answer value as a scalar number, string, boolean, or "
        "comma-separated list, matching the benchmark harness's expected format exactly."
    )
